export const STUDENTS = [
  { id: 'emma-johnson',      name: 'Emma Johnson' },
  { id: 'liam-smith',        name: 'Liam Smith' },
  { id: 'olivia-williams',   name: 'Olivia Williams' },
  { id: 'noah-brown',        name: 'Noah Brown' },
  { id: 'ava-jones',         name: 'Ava Jones' },
  { id: 'elijah-davis',      name: 'Elijah Davis' },
  { id: 'sophia-miller',     name: 'Sophia Miller' },
  { id: 'lucas-wilson',      name: 'Lucas Wilson' },
  { id: 'isabella-moore',    name: 'Isabella Moore' },
  { id: 'mason-taylor',      name: 'Mason Taylor' },
  { id: 'mia-anderson',      name: 'Mia Anderson' },
  { id: 'ethan-thomas',      name: 'Ethan Thomas' },
  { id: 'charlotte-jackson', name: 'Charlotte Jackson' },
  { id: 'aiden-white',       name: 'Aiden White' },
  { id: 'amelia-harris',     name: 'Amelia Harris' },
  { id: 'jackson-martin',    name: 'Jackson Martin' },
  { id: 'harper-thompson',   name: 'Harper Thompson' },
  { id: 'sebastian-garcia',  name: 'Sebastian Garcia' },
  { id: 'evelyn-martinez',   name: 'Evelyn Martinez' },
  { id: 'matthew-robinson',  name: 'Matthew Robinson' },
  { id: 'abigail-clark',     name: 'Abigail Clark' },
  { id: 'david-rodriguez',   name: 'David Rodriguez' },
  { id: 'emily-lewis',       name: 'Emily Lewis' },
];
